# This is a basic workflow to help you get started with Actions

name: File Validation

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.0
        with:
            php-version: 8.0

      # Runs a single command using the runners shell
      - name: Validate ChangeLog.md
        run: |
          cd $GITHUB_WORKSPACE &&
          php -r "\$file = file('ChangeLog.md');
          foreach(\$file as \$line){
            if(trim(\$line) == '' || trim(\$line)[0] == '#'){continue;}
            elseif(trim(\$line)[0] == '-'){
              if(!preg_match('/^( *)-( *)(.+)( *)\(([^)]+)\)$/', \$line)){
                echo 'ChangeLog.md file is not formatted correctly, please fix it.' . \"\n\";
                exit(1);
              }
            }
          }"
